AWSTemplateFormatVersion: "2010-09-09"
Description:  "AWS CloudFormation Template to create 2 node DocumentDB cluster"

Parameters:
  DocdbPort:
    Type: "String"
    Default: "27017"
  DocdbMasterUser:
    NoEcho: "true"
    Description : "The database admin account username"
    Type: "String"
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription : "Must begin with a letter and contain only alphanumeric characters."
  DocdbMasterPwd:
    NoEcho: "true"
    Description : "The database admin account password"
    Type: "String"
    MinLength: "1"
    MaxLength: "41"
  DocdbInstanceClass:
    Description : Instance class
    Default: "db.r6g.large"
    Type: "String"
    AllowedValues:
      - db.t3.medium
      - db.t4g.medium	
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge
      - db.r6g.large
      - db.r6g.xlarge                             
    ConstraintDescription : "Instance type must be of the ones supported for the region. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"  
  SgStack:
    Type: String
  BillingTag:
    Default: "vendorportal"
    Type: "String"
  OwnerTag:
    Default: "vendorportal"
    Type: "String"
  ProjectTag:
    Default: "vendorportal"
    Type: "String"
  Environment:
    Default: "dev"
    Type: "String"
  VpcBaseStack:
    Type: String
    AllowedPattern: '[A-Za-z][A-Za-z0-9-]{0,127}'
  KmsStack:
    Type: String
Conditions:
  IsHigherEnv: !Equals [ !Ref Environment, "prod" ]

Resources:
  VendorPortalDBParameterGroup:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties: 
      Description: "Cluster Parameter group for Vendorportal DocumentDB"
      Family: "docdb4.0"      
      Parameters: 
        audit_logs: "enabled"
        profiler: "enabled"
        profiler_threshold_ms: 500
        tls: "enabled"
        ttl_monitor: "enabled"
      Tags:
        -  Key: Name
           Value: !Sub "${ProjectTag}-docdb-${Environment}-paramgroup"  
        -  Key: Billing
           Value: !Ref BillingTag
        -  Key: Owner
           Value: !Ref OwnerTag
        -  Key: Project
           Value: !Ref ProjectTag
        -  Key: Environment
           Value: !Ref Environment
  VendorPortalDBCluster:
    Type: "AWS::DocDB::DBCluster"
    DeletionPolicy: Snapshot    
    Properties:
      AvailabilityZones: 
        Fn::GetAZs: 
          !Ref 'AWS::Region'
      BackupRetentionPeriod: 8      
      DBClusterParameterGroupName: !Ref VendorPortalDBParameterGroup
      DBSubnetGroupName: !Ref VendorPortalDBSubnetGroup
      DeletionProtection: True
      EnableCloudwatchLogsExports: 
        - "audit"
        - "profiler"
      EngineVersion: 4.0.0
      KmsKeyId: 
        Fn::ImportValue: !Sub "${KmsStack}::DocdbKMSKey"
      MasterUsername: !Ref DocdbMasterUser
      MasterUserPassword: !Ref DocdbMasterPwd
      Port: !Ref DocdbPort
      PreferredBackupWindow: "19:00-19:30"
      PreferredMaintenanceWindow: "sat:20:00-sat:20:30"
      StorageEncrypted: True
      Tags:
        -  Key: Name
           Value: !Sub "${ProjectTag}-docdb-${Environment}-Cluster"   
        -  Key: Billing
           Value: !Ref BillingTag
        -  Key: Owner
           Value: !Ref OwnerTag
        -  Key: Project
           Value: !Ref ProjectTag
        -  Key: Environment
           Value: !Ref Environment
      VpcSecurityGroupIds:
        -  Fn::ImportValue: !Sub "${SgStack}::DocdbSecurityGroup"
  VendorPortalDBInstance01:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      AutoMinorVersionUpgrade: True
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      DBClusterIdentifier: !Ref VendorPortalDBCluster
      DBInstanceClass: !Ref DocdbInstanceClass      
      PreferredMaintenanceWindow: "sat:20:00-sat:20:30"
      Tags:
        -  Key: Name
           Value: !Sub "${ProjectTag}-docdb-${Environment}-Instance-01"    
        -  Key: Billing
           Value: !Ref BillingTag
        -  Key: Owner
           Value: !Ref OwnerTag
        -  Key: Project
           Value: !Ref ProjectTag
        -  Key: Environment
           Value: !Ref Environment    
  VendorPortalDBInstance02:
    Condition: IsHigherEnv
    Type: "AWS::DocDB::DBInstance"
    Properties:
      AutoMinorVersionUpgrade: True
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      DBClusterIdentifier: !Ref VendorPortalDBCluster
      DBInstanceClass: !Ref DocdbInstanceClass      
      PreferredMaintenanceWindow: "sat:20:00-sat:20:30"
      Tags: 
        -  Key: Name
           Value: !Sub "${ProjectTag}-docdb-${Environment}-Instance-02"  
        -  Key: Billing
           Value: !Ref BillingTag
        -  Key: Owner
           Value: !Ref OwnerTag
        -  Key: Project
           Value: !Ref ProjectTag
        -  Key: Environment
           Value: !Ref Environment   
  VendorPortalDBSubnetGroup: 
    Type: "AWS::DocDB::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Vendorportal DB subnet group"        
      SubnetIds: 
        - Fn::ImportValue: !Sub "${VpcBaseStack}::SubnetIdPrivateAz1"
        - Fn::ImportValue: !Sub "${VpcBaseStack}::SubnetIdPrivateAz2"
        - Fn::ImportValue: !Sub "${VpcBaseStack}::SubnetIdPrivateAz3"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectTag}-docdb-${Environment}-SubnetGroup"   
        - Key: Billing
          Value: !Ref BillingTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Environment
          Value: !Ref Environment
  VendorPortalDocdbEndpointSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${ProjectTag}/docdb_endpoint
      Type: String
      Value: !GetAtt VendorPortalDBCluster.Endpoint
      Description: Stores the docdb endpoint      
      Tags:
        Name: !Sub ${AWS::StackName}-endpoint
        Billinge: !Sub ${BillingTag}
        Environment: !Sub ${Environment}
        Owner: !Sub ${OwnerTag}
        Project: !Sub ${ProjectTag}
  VendorPortalDocdbPortSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${ProjectTag}/docdb_port
      Type: String
      Value: !GetAtt VendorPortalDBCluster.Port
      Description: Stores the docdb port      
      Tags:
        Name: !Sub ${AWS::StackName}-port
        Billinge: !Sub ${BillingTag}
        Environment: !Sub ${Environment}
        Owner: !Sub ${OwnerTag}
        Project: !Sub ${ProjectTag}         

  
Outputs:
  VendorPortalClusterId:
    Description: "ClusterId of Database"
    Value: !Ref VendorPortalDBCluster
    Export:
      Name: !Sub ${AWS::StackName}::VendorPortalClusterId
  ClusterEndpoint:
    Value: !GetAtt VendorPortalDBCluster.Endpoint
  ClusterPort:
    Value: !GetAtt VendorPortalDBCluster.Port
  EngineVersion:
    Value: "4.0.0"
